name: Update Dota 2 Pro Matches

on:
  schedule:
    - cron: '0 */6 * * *'  # каждые 6 часов
  workflow_dispatch:  # ручной запуск

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install requests
      
      - name: Run Dota parser
        env:
          MWS_TOKEN: ${{ secrets.MWS_TOKEN }}
          MWS_TABLE_ID: ${{ secrets.MWS_TABLE_ID }}
        run: python dota_parser.py
